# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0e\x42\x61lanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"3\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\"O\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x16\n\x0eoperation_type\x18\x03 \x01(\t\"W\n\x0fTransferRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x0c\n\x04note\x18\x04 \x01(\t\"L\n\x10TransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"L\n\x19TransactionHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x10\n\x08per_page\x18\x03 \x01(\x05\"\x8e\x01\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x13\n\x0breceiver_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x0c\n\x04note\x18\x07 \x01(\t\"U\n\x1aTransactionHistoryResponse\x12\"\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x0c.Transaction\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\x84\x01\n\x18\x41\x63\x63ountManagementService\x12/\n\ngetBalance\x12\x0f.BalanceRequest\x1a\x10.BalanceResponse\x12\x37\n\rupdateBalance\x12\x15.UpdateBalanceRequest\x1a\x0f.StatusResponse2\x9f\x01\n\x12TransactionService\x12\x37\n\x10initiateTransfer\x12\x10.TransferRequest\x1a\x11.TransferResponse\x12P\n\x15getTransactionHistory\x12\x1a.TransactionHistoryRequest\x1a\x1b.TransactionHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSRESPONSE']._serialized_start=17
  _globals['_STATUSRESPONSE']._serialized_end=67
  _globals['_BALANCEREQUEST']._serialized_start=69
  _globals['_BALANCEREQUEST']._serialized_end=102
  _globals['_BALANCERESPONSE']._serialized_start=104
  _globals['_BALANCERESPONSE']._serialized_end=155
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=157
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=236
  _globals['_TRANSFERREQUEST']._serialized_start=238
  _globals['_TRANSFERREQUEST']._serialized_end=325
  _globals['_TRANSFERRESPONSE']._serialized_start=327
  _globals['_TRANSFERRESPONSE']._serialized_end=403
  _globals['_TRANSACTIONHISTORYREQUEST']._serialized_start=405
  _globals['_TRANSACTIONHISTORYREQUEST']._serialized_end=481
  _globals['_TRANSACTION']._serialized_start=484
  _globals['_TRANSACTION']._serialized_end=626
  _globals['_TRANSACTIONHISTORYRESPONSE']._serialized_start=628
  _globals['_TRANSACTIONHISTORYRESPONSE']._serialized_end=713
  _globals['_ACCOUNTMANAGEMENTSERVICE']._serialized_start=716
  _globals['_ACCOUNTMANAGEMENTSERVICE']._serialized_end=848
  _globals['_TRANSACTIONSERVICE']._serialized_start=851
  _globals['_TRANSACTIONSERVICE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
